/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RequestRouteImport } from './routes/request'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CounsellorIndexRouteImport } from './routes/counsellor.index'
import { Route as CounsellorAlertsRouteImport } from './routes/counsellor.alerts'
import { Route as CounsellorTraceThreadIdRouteImport } from './routes/counsellor.trace.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorIndexRoute = CounsellorIndexRouteImport.update({
  id: '/counsellor/',
  path: '/counsellor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorAlertsRoute = CounsellorAlertsRouteImport.update({
  id: '/counsellor/alerts',
  path: '/counsellor/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorTraceThreadIdRoute = CounsellorTraceThreadIdRouteImport.update({
  id: '/counsellor/trace/$threadId',
  path: '/counsellor/trace/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/portal': typeof PortalRoute
  '/request': typeof RequestRoute
  '/status': typeof StatusRoute
  '/counsellor/alerts': typeof CounsellorAlertsRoute
  '/admin/': typeof AdminIndexRoute
  '/counsellor/': typeof CounsellorIndexRoute
  '/counsellor/trace/$threadId': typeof CounsellorTraceThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/portal': typeof PortalRoute
  '/request': typeof RequestRoute
  '/status': typeof StatusRoute
  '/counsellor/alerts': typeof CounsellorAlertsRoute
  '/admin': typeof AdminIndexRoute
  '/counsellor': typeof CounsellorIndexRoute
  '/counsellor/trace/$threadId': typeof CounsellorTraceThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/checkin': typeof CheckinRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/portal': typeof PortalRoute
  '/request': typeof RequestRoute
  '/status': typeof StatusRoute
  '/counsellor/alerts': typeof CounsellorAlertsRoute
  '/admin/': typeof AdminIndexRoute
  '/counsellor/': typeof CounsellorIndexRoute
  '/counsellor/trace/$threadId': typeof CounsellorTraceThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/checkin'
    | '/help'
    | '/history'
    | '/portal'
    | '/request'
    | '/status'
    | '/counsellor/alerts'
    | '/admin/'
    | '/counsellor/'
    | '/counsellor/trace/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/checkin'
    | '/help'
    | '/history'
    | '/portal'
    | '/request'
    | '/status'
    | '/counsellor/alerts'
    | '/admin'
    | '/counsellor'
    | '/counsellor/trace/$threadId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/checkin'
    | '/help'
    | '/history'
    | '/portal'
    | '/request'
    | '/status'
    | '/counsellor/alerts'
    | '/admin/'
    | '/counsellor/'
    | '/counsellor/trace/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CheckinRoute: typeof CheckinRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  PortalRoute: typeof PortalRoute
  RequestRoute: typeof RequestRoute
  StatusRoute: typeof StatusRoute
  CounsellorAlertsRoute: typeof CounsellorAlertsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CounsellorIndexRoute: typeof CounsellorIndexRoute
  CounsellorTraceThreadIdRoute: typeof CounsellorTraceThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor/': {
      id: '/counsellor/'
      path: '/counsellor'
      fullPath: '/counsellor/'
      preLoaderRoute: typeof CounsellorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor/alerts': {
      id: '/counsellor/alerts'
      path: '/counsellor/alerts'
      fullPath: '/counsellor/alerts'
      preLoaderRoute: typeof CounsellorAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor/trace/$threadId': {
      id: '/counsellor/trace/$threadId'
      path: '/counsellor/trace/$threadId'
      fullPath: '/counsellor/trace/$threadId'
      preLoaderRoute: typeof CounsellorTraceThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CheckinRoute: CheckinRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  PortalRoute: PortalRoute,
  RequestRoute: RequestRoute,
  StatusRoute: StatusRoute,
  CounsellorAlertsRoute: CounsellorAlertsRoute,
  AdminIndexRoute: AdminIndexRoute,
  CounsellorIndexRoute: CounsellorIndexRoute,
  CounsellorTraceThreadIdRoute: CounsellorTraceThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
